### ISSUE TITLE
Inaccurate Documentation

### ISSUE THREAD

**Issue by emozley** [Roblox/roact-rodux#24]
The API reference under [https://roblox.github.io/roact-rodux/api-reference/#storeprovider](StoreProvider) reports that Roact does not yet support fragments, which is not the case.

**Comment by LPGhatguy** [comment]
We haven't updated Roact-Rodux to work with fragments yet, so this restriction is still here. 😅 

Would you be interested in filing a PR to replace the usage of `Roact.oneChild` with fragments and update this documentation?

**Comment by ThePotato97** [comment]
Going to remove the warning yet? #27 made it use fragments
