### ISSUE TITLE
Documentation page does not support dark theme

### ISSUE THREAD

**Issue by FilteredStudio** [Roblox/roact-rodux#45]
GitHub recently released dark theme, Material for MkDocs also recently added this feature, however the docs page for this specific library doesn't seem to support it?
![image](https://user-images.githubusercontent.com/41757236/104112276-9756c780-52e4-11eb-969c-cd1a828cef7c.png)

**Comment by Nickuhhh** [comment]
https://github.com/Roblox/roact-rodux/pull/44
